### ISSUE TITLE
Calculation Logic:

### ISSUE THREAD

**Issue by RlucSal** [kaiwright/dishcovery#14]
Acceptance Criteria:
- [ ] Develop algorithms to convert ingredient quantities into standardised units for carbon footprint calculations.
- [ ] Regularly update the carbon footprint data in the database to ensure accuracy.
- [ ] Provide a clear breakdown of how the total carbon footprint is calculated.

**Comment by kaiwright** [comment]
User story:
As a user, I want to be able to see an accurate calculation of my carbon footprint, displayed in a way that is easy to understand.

**Comment by RlucSal** [comment]
We have decided to take a different approach, and as a result, the issue reported here is no longer applicable or relevant to the current state of the project.
